spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=TODOLIST_DB;encrypt=true;trustServerCertificate=true;
    username: sa
    password: htet

    hikari:
      maximum-pool-size: 100
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
